# Generated by Django 2.2.13 on 2021-01-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErshouHuxingcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('huxing', models.TextField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ershou_huxingcount',
                'managed': True,
            },
        ),
    ]
